package com.example;


public class Main
{
    public static void main( String[] args )
    {
        String text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada, sem porta ornare lobortis, massa massa volutpat eros, vel mattis lorem ante vel magna. In nec dolor a ex tempor ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer semper nisl vitae elit porttitor, placerat efficitur ipsum blandit. Aliquam egestas molestie dolor id interdum. Donec venenatis odio sed massa elementum interdum. Mauris posuere ultricies leo, id dapibus dui sollicitudin eu. Fusce ultricies consequat leo ut posuere. " +
                "Integer bibendum nec metus vitae tincidunt. Nunc a diam enim. Duis porttitor sodales lectus elementum euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla volutpat turpis vel odio luctus sodales. In erat urna, tristique et suscipit molestie, semper nec diam. Nam faucibus in lorem vitae mattis. Sed eget libero sapien. Curabitur aliquet suscipit tellus ut convallis. Sed nec egestas elit. " +
                "Nam ut orci pulvinar, posuere nisl eget, pulvinar ante. Sed elementum, magna sed hendrerit finibus, felis massa commodo nisi, at pretium erat justo vitae est. Nam commodo condimentum ultricies. Morbi elementum ultrices dictum. Mauris pellentesque quis neque ut vestibulum. Phasellus non nunc in neque pellentesque dictum in ac ligula. Mauris fringilla metus nec nisi ornare aliquet. Donec non purus ac purus finibus pellentesque. Vestibulum sagittis ligula at nulla gravida, ullamcorper pellentesque tortor dignissim. Donec diam leo, malesuada vel dolor eget, volutpat aliquet mi. Ut consectetur sem a nulla scelerisque, ornare rhoncus massa sollicitudin. Mauris finibus pellentesque maximus. Ut vitae neque elit. Proin malesuada massa quam, nec porttitor elit vestibulum ac. " +
                "Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce a porta mauris. Sed dignissim ut arcu eu luctus. In consectetur vestibulum scelerisque. Aliquam placerat finibus nunc ac convallis. Sed eget sapien mauris. Praesent sed luctus magna, nec condimentum justo. Suspendisse consequat orci sed neque venenatis, sed faucibus turpis placerat. Nam vulputate dictum venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In vulputate hendrerit dolor. Duis neque purus, cursus et suscipit id, ullamcorper at magna. Pellentesque consectetur aliquam auctor. Praesent a dolor posuere, pretium arcu nec, varius ex. Sed malesuada orci quis nunc pellentesque sagittis. " +
                "Duis molestie sed dui sit amet dignissim. Curabitur commodo nisi non elit tincidunt, sed gravida sem euismod. Curabitur et pharetra neque. Donec sagittis sem est, id ornare nulla aliquet eget. Nunc ac sollicitudin ante. Ut lacinia sit amet urna interdum vehicula. Praesent finibus nisl scelerisque euismod porttitor. Integer vitae tempor libero. Nunc vehicula tellus vel est dictum varius vel sed ante. Mauris viverra, diam vitae accumsan feugiat, mauris elit consectetur ex, sit amet luctus tellus elit at lectus. Mauris nibh elit, venenatis vel sodales eget, dapibus ac ipsum. " +
                "Maecenas lobortis dui id mattis posuere. Sed eget est lobortis, ornare felis et, semper odio. Etiam nunc ipsum, mattis nec turpis in, pharetra dapibus turpis. Curabitur sollicitudin pharetra ligula, a gravida lectus consectetur vel. Proin in elit maximus, lacinia nulla at, pulvinar lectus. Pellentesque id gravida neque. Nulla ex elit, tempor non metus sit amet, dapibus venenatis. ";

        String otherText = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum." +
                "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.";


        TextFormatter formatter = new TextFormatterImpl();
        formatter.showText(text);
        System.out.println();
        formatter.showText(otherText);
    }
}
